travis:
  secure:
    BINSTAR_TOKEN: V5ghnPTFkp6yMEWtNSpmUEW/YPNNUqi0iiRKqdZ1XEhiAxljAww9grMA5YqewTYmOdpEut18827GtsMamDKIV3cdK27VttInJPtpZqXjZ5v2kXN4uHrovsDR9SkMz0MAKrPOPhVBOJAE9PU6tLtRAKmwm4z6Om2jdEgBrcNl5l8fzVBuGiSUgQ9LsiwZnIyz48ApZoFq0RTusnVYg0oaG/gX3hymVYXbF1VWPy3lEbyhOva+X3RoI+/rYsZIaHl3EXi8hcvt4XVIyafumu1COh2zuyAuSMnd9s1KaQ7HZ4T6v+U8/qLwaZ4zQ/+8Y1vlANTmIBZbWgYOKABF5+oV3pdEKa9+tK0hhMCksW3lKy4aM5jM0nABBo66lYzLjHF0TeibFyd0aUDZYaZD080SWhfKC2CFLFsI/jbCML021k5iC9ufHmtj7+AdYIH6VIatsdHSnWz9cBIa6mk+AjDkUA+GQG0N2WllhyT6wWfZ1Flfj7UmuwjbJTl3mq7iAeuKAelhT7H8zzZVPh7CnJCCX6or9h0PMjUVIOMuN9v3VN9EWUOF506cKRMTEA6hN6Jg6l0x8JpqxrAbraCcNbU+kJnSFJ97AS5zXM2psOfThMgS0Bcth3h5YSEmqGJRipNEoFrw5oRe3DARKUNeeGPL2D6RYAtUFdKkiO9/PHbQBoA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
